In [4]:
l=list(map(str,input().split()))
r=[]
for i in range(len(l)):
    r.append(int(l[i][len(l[i])//2]))
print(sum(r))

123 345 567
12


# Data Analysis


In [6]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [7]:
np.__version__

'1.20.1'

# Array creation
 -array() is the sub module in numpy module
 -np.array(iterable)

In [11]:
t=np.array((2,4,43,545,56))
t

array([  2,   4,  43, 545,  56])

In [12]:
print(np.array([3,54,54,5,6,456]))

[  3  54  54   5   6 456]


In [13]:
s=np.array([456.45,66453,4545.4,55.546])
s

array([4.5645e+02, 6.6453e+04, 4.5454e+03, 5.5546e+01])

In [14]:
s=np.array([456.45,66453,4545.4,55.546],dtype='int')
s

array([  456, 66453,  4545,    55])

In [15]:
r=np.array(range(10))
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(np.array(range(300,200,-7)))

[300 293 286 279 272 265 258 251 244 237 230 223 216 209 202]


In [26]:
li=np.array([[6,5,67],[6,87,8]])
print(li)

[[ 6  5 67]
 [ 6 87  8]]


In [27]:
li.size

6

In [28]:
li.shape

(2, 3)

In [29]:
li.dtype


dtype('int32')

In [30]:
li.itemsize

4

In [31]:
r.itemsize

4

In [32]:
dd=np.array([3,4,5,7],ndmin=10)
print(dd)

[[[[[[[[[[3 4 5 7]]]]]]]]]]


In [33]:
print(dd[0])

[[[[[[[[[3 4 5 7]]]]]]]]]


In [35]:
i=np.eye(4)
print(i)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
c=np.zeros(5)
print(c)

[0. 0. 0. 0. 0.]


In [49]:
z=np.eye(4,5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [51]:
z=np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
o=np.ones((4,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
o=np.ones(5,dtype='int')
o

array([1, 1, 1, 1, 1])

In [55]:
f=np.full(4,'hi')
f

array(['hi', 'hi', 'hi', 'hi'], dtype='<U2')

In [58]:
f=np.full((3,3),'hi')
f

array([['hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi']], dtype='<U2')

In [59]:
f.fill(4)
f

array([['4', '4', '4'],
       ['4', '4', '4'],
       ['4', '4', '4']], dtype='<U2')

In [60]:
f

array([['4', '4', '4'],
       ['4', '4', '4'],
       ['4', '4', '4']], dtype='<U2')

In [62]:
ln=np.linspace(10,200,13)
ln

array([ 10.        ,  25.83333333,  41.66666667,  57.5       ,
        73.33333333,  89.16666667, 105.        , 120.83333333,
       136.66666667, 152.5       , 168.33333333, 184.16666667,
       200.        ])

In [63]:
ar=np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
print(np.arange(20,100,7))

[20 27 34 41 48 55 62 69 76 83 90 97]


In [67]:
print(np.arange(100,20,-7))

[100  93  86  79  72  65  58  51  44  37  30  23]


In [77]:
ar.reshape(5,5)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
r2=np.arange(100,20,-4)
r2

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24])

# Random()


In [6]:
import numpy as np
np.random.randint(60,300)

198

In [9]:
lw,up=int(input()),int(input())
ri=np.random.randint(lw,up,8)
ri

100
500


array([119, 298, 457, 422, 214, 146, 293, 267])

In [10]:
lw,up=int(input()),int(input())
ri=np.random.randint(lw,up,8)
ri.reshape(2,4)

100
500


array([[469, 272, 322, 445],
       [468, 431, 205, 320]])

In [11]:
ri

array([469, 272, 322, 445, 468, 431, 205, 320])

In [12]:
ri=np.random.randint(99,200,8)
ri.reshape(8,1)

array([[112],
       [169],
       [101],
       [120],
       [181],
       [110],
       [167],
       [100]])

In [13]:
ri

array([112, 169, 101, 120, 181, 110, 167, 100])

In [15]:
np.random.random((2,3))


array([[0.85524458, 0.10104105, 0.05059655],
       [0.76856738, 0.62801567, 0.87955384]])

np.random.randn(4,3)

In [20]:
np.linspace(3,10)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [21]:
np.random.rand(4,3)

array([[0.59175234, 0.06897398, 0.67878048],
       [0.29443531, 0.31921519, 0.68130708],
       [0.91814908, 0.41402959, 0.68074082],
       [0.59152445, 0.11083294, 0.55669221]])

# Accesing the array elements
- using index(3 types)
- +ve,-ve and fancy index
- -->condition based index

In [35]:
r=np.random.randint(50,200,25).reshape(5,-2)
r

array([[172, 140,  90,  91,  54],
       [ 50,  75,  52, 131, 127],
       [197,  57, 158, 119,  96],
       [156, 166, 148, 192,  78],
       [165,  75, 102,  96, 132]])

In [42]:
arn=np.arange(50,100,2).reshape(-1,5)
arn

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [36]:
arn[::]

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [37]:
arn[::2]

array([[50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [43]:
arn[:1:4]

array([[50, 52, 54, 56, 58]])

In [44]:
arn[:1:3]

array([[50, 52, 54, 56, 58]])

In [45]:
arn[:,1:4]

array([[52, 54, 56],
       [62, 64, 66],
       [72, 74, 76],
       [82, 84, 86],
       [92, 94, 96]])

In [48]:
for i in arn[:,1:4]:
    print(i,end=",")

[52 54 56],[62 64 66],[72 74 76],[82 84 86],[92 94 96],

In [54]:
sub=arn[:,1:4]
for i in sub:
    for val in i:
        if val%2==0:
            print(val,end=",")

52,54,56,62,64,66,72,74,76,82,84,86,92,94,96,

In [55]:
arn

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [59]:
arn[1:3:2]

array([[60, 62, 64, 66, 68]])

In [64]:
arn[::2,2:]

array([[54, 56, 58],
       [74, 76, 78],
       [94, 96, 98]])

In [65]:
r<100

array([[False, False,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False,  True, False, False,  True],
       [False, False, False, False,  True],
       [False,  True, False,  True, False]])

In [66]:
r[r<100]

array([90, 91, 54, 50, 75, 52, 57, 96, 78, 75, 96])

In [67]:
print(r+arn)

[[222 192 144 147 112]
 [110 137 116 197 195]
 [267 129 232 195 174]
 [236 248 232 278 166]
 [255 167 196 192 230]]


In [68]:
print(r-arn)

[[122  88  36  35  -4]
 [-10  13 -12  65  59]
 [127 -15  84  43  18]
 [ 76  84  64 106 -10]
 [ 75 -17   8   0  34]]


In [69]:
print(r*arn)

[[ 8600  7280  4860  5096  3132]
 [ 3000  4650  3328  8646  8636]
 [13790  4104 11692  9044  7488]
 [12480 13612 12432 16512  6864]
 [14850  6900  9588  9216 12936]]


In [70]:
print(sum(arn))

[350 360 370 380 390]


In [71]:
r.sum()

2919

In [73]:
r>100

False

In [74]:
r<100

False

In [75]:
print(r)

100


In [76]:
arn

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [77]:
arn[0]

array([50, 52, 54, 56, 58])

In [78]:
sum(arn[0])

270

In [80]:
sum(arn[::2,::2])

array([210, 222, 234])

In [83]:
np.log(10)

2.302585092994046

In [84]:
np.log(1)

0.0

In [85]:
np.log(2)

0.6931471805599453

In [86]:
np.log2(2)

1.0

In [89]:
np.log2(4)

2.0

In [90]:
np.exp(1)

2.718281828459045

In [91]:
np.exp(np.log(1))

1.0

In [92]:
np.log(np.exp(1))

1.0

In [93]:
#vectorized funcions in numpy

In [95]:
def greater(a,b):
    return a if a>b else b
greater(3,4)

4

In [100]:
greater([3,4,1],[3,3,1])

[3, 4, 1]

In [103]:
li,li2=[9,3,1],[4,10,4]
new=[]
for a,b in zip(li,li2):
    new.append(a) if a>b else new.append(b)
print(new)

[9, 10, 4]


In [104]:
g=np.vectorize(greater)
g(li,li2)

array([ 9, 10,  4])